### ISSUE TITLE
Face up and train card count not keeping in sync

### ISSUE THREAD

**Issue by jarinbj** [byucs340ta/Winter2019#117] opened 2019-04-02 01:34 UTC
See screenshot
![image](https://user-images.githubusercontent.com/36678114/55369760-1df63800-54b5-11e9-9da3-e157efc6bc44.png)

**Comment by coyRocks3** [comment] 2019-04-05 16:25
Duplicate of issue #120

**Closed by coyRocks3** 2019-04-05 16:25 UTC
Labels: P3: Affects Gameplay, Team 13
