### ISSUE TITLE
Team 36: Images not loading

### ISSUE THREAD

**Issue by jeremypleb** [byucs340ta/Winter2019#66] opened 2019-04-01 20:25 UTC
The images are slow to load sometimes, and so drawing faceup train cards is difficult (don't  know which card is which). The decks don't refresh so there is always a broken image there, if it doesn't load initially.

**Comment by jaydenmilne** [comment] 2019-04-01 20:40
Try this with good wifi, the room we were in has poor internet

**Comment by jaydenmilne** [comment] 2019-04-03 17:23
I've had Chrome throttle the internet to "Slow 3G" and while it would take a second for the images to pop in, they always would

**Comment by brennonbrimhall** [comment] 2019-04-03 20:16
Closing because we can't reproduce.

**Closed by brennonbrimhall** 2019-04-03 20:16 UTC
Labels: P3: Affects Gameplay, Team 36

**Comment by jaydenmilne** [comment] 2019-04-03 20:30
We did observe this, but it only happened when it took 15+ seconds to load a ~10 kb SVG file. We are prepared to accept slow loading when you have sub dial up internet speeds.
