### ISSUE TITLE
Team 10: Empty Train deck

### ISSUE THREAD

**Issue by Eric140** [byucs340ta/Winter2019#8] opened 2019-04-01 17:46 UTC
Still can draw from Deck, advances turn for player, but not the rest of the players. It looks like no cards are added to player’s hand.
It appears that if there are any cards in the discard, that upon being shuffled back in, the discard is not cleared, so when the deck empties again, it reshuffles the same cards back into the deck.

**Comment by Jacob-Baldwin** [comment] 2019-04-03 15:43
Resolved in merge request [#98](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/98).

Duplicate of #113? Closing.

**Closed by Jacob-Baldwin** 2019-04-03 15:43 UTC
Labels: P3: Affects Gameplay, Team 10
